### ISSUE TITLE
Docker-busybox-java uses opposed naming convention to official Java

### ISSUE THREAD

**Issue by luebken** [jeanblanchard/docker-busybox-java#7]
As noted in https://github.com/jeanblanchard/docker-busybox-java#tags `docker-busy-box` uses the single digit tags like `8` to refer to the runtime aka JRE. The JDK is qualified via `jdk8`.

The official java repository uses an opposed convention: https://registry.hub.docker.com/_/java/ e.g. `java:8` refers to `java:8-jdk`.

**Comment by jeanblanchard** [comment]
This is by design.
Note that it's not a jre, but a server-jre, which is what you typically want to run a server, no need for a jdk.
