### ISSUE TITLE
Please kick off new build to pick up latest busybox image or opkg-install will not work

### ISSUE THREAD

**Issue by brikis98** [jeanblanchard/docker-busybox-java#8]
Apparently, the progrium/busybox image has changed the download URL for opkg from `http://downloads.openwrt.org/snapshots/trunk/x86_64/generic/packages/base/` to `http://downloads.openwrt.org/snapshots/trunk/x86/64/packages/base/`. Therefore, we need a new image of docker-busybox-java to be built and pushed to Docker Hub, as any attempt to use `opkg-install` on the current image fails with the following error:

```
Downloading http://downloads.openwrt.org/snapshots/trunk/x86_64/generic/packages/base/Packages.gz.
wget: server returned error: HTTP/1.1 404 Not Found
```

**Comment by jeanblanchard** [comment]
Unfortunately, the upstream busybox image does nto work

**Comment by jeanblanchard** [comment]
There is not much hope for opkg to work again on the busybox image, so I created a new image based on Alpine Linux.
See [jeanblanchard/java](https://registry.hub.docker.com/u/jeanblanchard/java/) ([GitHub](https://github.com/jeanblanchard/docker-java)).
