### ISSUE TITLE
opkg.conf update missing?

### ISSUE THREAD

**Issue by vencik** [jeanblanchard/docker-busybox-java#9]
Hello,

I'm having trouble installing packages; I've noticed that in /etc/opkg.conf, the repo paths are old (see
https://github.com/progrium/busybox/commit/4481c0ee2a8217aeb1233962a8a99ae2d65c404d).
Perhaps a re-build is necessary?
Or is it on my side?

Thanks

**Comment by jeanblanchard** [comment]
See #8 or the big bold warning in the README. OPKG is broken in the base busybox image, and probably will not be fixed in the near future. I suggest you switch to my new jeanblanchard/java image, which is based on Alpine Linux.
